# Development image. Not suitable for production -- use Dockerfile for that.
ARG RUBY_VERSION=3.4.10
FROM docker.io/library/ruby:$RUBY_VERSION

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential git libpq-dev libvips libyaml-dev pkg-config postgresql-client curl && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

WORKDIR /rails

ENV BUNDLE_PATH="/usr/local/bundle"

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .
RUN chmod +x bin/*

EXPOSE 3000
CMD ["bin/docker-dev-entrypoint"]
