# Turns a client supplied filename into something safe to store and to echo
# back in a Content-Disposition header.
#
# Uploaded names are never trusted: they may contain directory components, null
# bytes, control characters or thousands of code points. The sanitized name is
# only ever used as a label and inside download headers -- storage keys are
# generated by Active Storage and never derived from it.
class SafeFilename
  # Long enough for real world names, short enough to stay well inside the
  # 255 byte limit of common filesystems once encoded.
  MAX_LENGTH = 180

  FALLBACK = "unnamed-file".freeze

  BACKSLASH = "\\".freeze
  SEPARATOR = "/".freeze

  # Characters that are illegal on Windows or that confuse header parsers.
  UNSAFE_CHARACTERS = /[<>:"|?*]/

  class << self
    def call(value)
      name = normalize(value)
      name = strip_directories(name)
      name = strip_unsafe_characters(name)
      name = collapse_whitespace(name)
      name = reject_relative_paths(name)
      name = truncate_preserving_extension(name)

      name.presence || FALLBACK
    end

    private
      def normalize(value)
        value.to_s.unicode_normalize(:nfc)
      rescue ArgumentError, Encoding::CompatibilityError
        # Invalid byte sequences are scrubbed rather than raising.
        value.to_s.scrub("")
      end

      # Handles "../../etc/passwd", "C:\Windows\system32\x" and anything else
      # carrying a path. Only the final component survives.
      def strip_directories(name)
        name.tr(BACKSLASH, SEPARATOR).split(SEPARATOR).last.to_s
      end

      def strip_unsafe_characters(name)
        name
          .delete("\u0000-\u001F\u007F")        # control characters, including NUL
          .gsub(UNSAFE_CHARACTERS, "-")
          .sub(/[.\s]+\z/, "")                  # trailing dots and spaces
      end

      def collapse_whitespace(name)
        name.gsub(/\s+/, " ").strip
      end

      # A name made only of dots is never a real file name, and "." and ".."
      # must never survive sanitization.
      def reject_relative_paths(name)
        name.match?(/\A\.*\z/) ? "" : name
      end

      def truncate_preserving_extension(name)
        return name if name.length <= MAX_LENGTH

        extension = File.extname(name)
        extension = "" if extension.length > 16 # not really an extension
        base = name.delete_suffix(extension)

        "#{base[0, MAX_LENGTH - extension.length]}#{extension}"
      end
  end
end
